/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CompetitorsRouteImport } from './routes/competitors'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeadlinesRouteImport } from './routes/deadlines'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DraftsRouteImport } from './routes/drafts'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SupplierRouteImport } from './routes/supplier'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TendersRouteImport } from './routes/tenders'
import { Route as IndexRouteImport } from './routes/index'

const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsRoute = CompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadlinesRoute = DeadlinesRouteImport.update({
  id: '/deadlines',
  path: '/deadlines',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsRoute = DraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierRoute = SupplierRouteImport.update({
  id: '/supplier',
  path: '/supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TendersRoute = TendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/competitors': typeof CompetitorsRoute
  '/customer': typeof CustomerRoute
  '/dashboard': typeof DashboardRoute
  '/deadlines': typeof DeadlinesRoute
  '/documents': typeof DocumentsRoute
  '/drafts': typeof DraftsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/supplier': typeof SupplierRoute
  '/support': typeof SupportRoute
  '/tenders': typeof TendersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/competitors': typeof CompetitorsRoute
  '/customer': typeof CustomerRoute
  '/dashboard': typeof DashboardRoute
  '/deadlines': typeof DeadlinesRoute
  '/documents': typeof DocumentsRoute
  '/drafts': typeof DraftsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/supplier': typeof SupplierRoute
  '/support': typeof SupportRoute
  '/tenders': typeof TendersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/competitors': typeof CompetitorsRoute
  '/customer': typeof CustomerRoute
  '/dashboard': typeof DashboardRoute
  '/deadlines': typeof DeadlinesRoute
  '/documents': typeof DocumentsRoute
  '/drafts': typeof DraftsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/supplier': typeof SupplierRoute
  '/support': typeof SupportRoute
  '/tenders': typeof TendersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/competitors'
    | '/customer'
    | '/dashboard'
    | '/deadlines'
    | '/documents'
    | '/drafts'
    | '/notifications'
    | '/onboarding'
    | '/settings'
    | '/supplier'
    | '/support'
    | '/tenders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/competitors'
    | '/customer'
    | '/dashboard'
    | '/deadlines'
    | '/documents'
    | '/drafts'
    | '/notifications'
    | '/onboarding'
    | '/settings'
    | '/supplier'
    | '/support'
    | '/tenders'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/competitors'
    | '/customer'
    | '/dashboard'
    | '/deadlines'
    | '/documents'
    | '/drafts'
    | '/notifications'
    | '/onboarding'
    | '/settings'
    | '/supplier'
    | '/support'
    | '/tenders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CompetitorsRoute: typeof CompetitorsRoute
  CustomerRoute: typeof CustomerRoute
  DashboardRoute: typeof DashboardRoute
  DeadlinesRoute: typeof DeadlinesRoute
  DocumentsRoute: typeof DocumentsRoute
  DraftsRoute: typeof DraftsRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  SupplierRoute: typeof SupplierRoute
  SupportRoute: typeof SupportRoute
  TendersRoute: typeof TendersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors': {
      id: '/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof CompetitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deadlines': {
      id: '/deadlines'
      path: '/deadlines'
      fullPath: '/deadlines'
      preLoaderRoute: typeof DeadlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts': {
      id: '/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof DraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier': {
      id: '/supplier'
      path: '/supplier'
      fullPath: '/supplier'
      preLoaderRoute: typeof SupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenders': {
      id: '/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof TendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CompetitorsRoute: CompetitorsRoute,
  CustomerRoute: CustomerRoute,
  DashboardRoute: DashboardRoute,
  DeadlinesRoute: DeadlinesRoute,
  DocumentsRoute: DocumentsRoute,
  DraftsRoute: DraftsRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  SettingsRoute: SettingsRoute,
  SupplierRoute: SupplierRoute,
  SupportRoute: SupportRoute,
  TendersRoute: TendersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
